export const TODO_ADD = 'TODO_ADD';
export const TODO_TOGGLE = 'TODO_TOGGLE';
export const TODO_DELETE = 'TODO_DELETE';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const TOGGLE_SHOW_COMPLETED = 'TOGGLE_SHOW_COMPLETED';
